name: xeus-javascript-wasm-build
channels:
  - conda-forge
dependencies:
  - anywidget
  - cmake
  - emsdk >=3.1.46
  - empack >=3.2.0
  - jupyter_server  # to enable contents
  - jupyterlite-core
  - jupyterlite-xeus
  - notebook >=7,<8  # to include the extension to switch between JupyterLab and Notebook
