name: xeus-javascript-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite >=2.0.0,<3.0
  - xeus >=4.0.1,<5.0
  - xtl >=0.7,<0.8
